[mypy]
python_version = 3.13
ignore_missing_imports = True
disallow_untyped_defs = False
strict_optional = True

[mypy-ssb_konjunk.dash.components.__init__]
ignore_errors = True

[mypy-ssb_konjunk.dash.components.internal]
ignore_errors = True
